config/routes.rb
RBlog::Application.routes.draw do

  get "api/index"

  get "api/show"
  
  get "post/index"

  get "post/new"

  get "post/view"

  get "post/update"

  put "post/new"

  put "post/update_post"

  put "post/new_comment"

  put "post/like_post"

  put "post/like_comment"

  put "post/like_like"

  delete "post/delete"

  root :to => 'post#index'
  
  authenticated :user do
    root :to => 'post#index'
  end
  
  devise_for :users
  resources :users
  
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :article_id, :author_mail, :author_name, :content, :tag, :title, :type
  validates_presence_of :author_mail, :author_name, :content
  validates :author_mail, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }


  def comments_hash
  	if self.comments.count == 0
  		return self.attributes
  	else
  		comments_ary = []
  		self.comments.each do |c|
  			comments_ary << c.comments_hash
  		end
  		likes_ary = []
  		self.likes.each do |l|
  			likes_ary << l.likes_hash
  		end
  		result = self.attributes.merge({:comments => comments_ary})
  		result.merge!({:likes => likes_ary}) if self.likes.count > 0

  		return result
  	end
  end
end

app/models/comment.rb
class Comment < Article
  has_many :likes, :dependent => :destroy, :as => :likeable
  has_many :comments, :dependent => :destroy, :foreign_key => 'article_id'
  belongs_to :posts
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :likeable_id, :likeable_type, :user_id
  belongs_to :likeable, :polymorphic => true
  has_many :likes, :dependent => :destroy, :as => :likeable


  def likes_hash
  	if self.likes.count == 0
  		return self.attributes
  	else
  		likes_ary = []
  		self.likes.each do |l|
  			likes_ary << l.likes_hash
  		end
  		result = self.attributes.merge({:likes => likes_ary})

  		return result
  	end
  end
end

app/models/post.rb
class Post < Article
  validates_presence_of :title
  has_many :likes, :dependent => :destroy, :as => :likeable
  has_many :comments, :dependent => :destroy, :foreign_key => 'article_id'
  has_many :child_comments, :through => :comments, :source => :comments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

	def index
		@posts = Post.all
		render :json => @posts
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments
		@child_comments = @post.child_comments
    	@comment_total = 0
	    if !@post.comments.empty?
	      @comment_total += @post.comments.size
	    end
	    if !@post.child_comments.empty?
	      @comment_total += @post.child_comments.size
	    end
		render :json => {:post => @post.comments_hash}
	end

	def create
		render :json => Post.create(params[:post])
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    if !params[:tag].nil? && !params[:tag].empty?
      puts params[:tag]
      @posts = Post.where("tag like?", "%#{params[:tag]}%")
    else
      @posts = Post.all
    end
  end

  def new
  	if !params[:post].nil? && !params[:post].empty?
  		@post = Post.new(params[:post])
  		if @post.save
        flash[:notice] = "The post has been successfully created."
        respond_to do |format|
          format.html { redirect_to :action => 'view', :id => @post.id }
          format.json { render json: @post.id, status: :created }
        end
  		end
  	else
  		@post = Post.new
  	end
  end

  def view
    @notice = params[:notice] unless params[:notice].nil? && params[:notice].blank?
  	@post = Post.find(params[:id])
    @comment_total = 0
    if !@post.comments.empty?
      @comment_total += @post.comments.size
    end
    if !@post.child_comments.empty?
      @comment_total += @post.child_comments.size
    end
  end

  def update
    @post = Post.find(params[:id])
  end

  def update_post
    @post = Post.find(params[:post][:id])
    if @post.update_attributes(params[:post])
      flash[:updated] = "The post has been successfully updated."
      respond_to do |format|
        format.html { redirect_to :action => 'view', :id => @post.id }
        format.json { render json: @post.id, status: :created }
      end
    else
      render :action => 'update'
    end
  end

  def delete 
    @post = Post.find(params[:id])
    @post.destroy
    flash[:deleted] = "The post has been successfully deleted."
    redirect_to :action => 'index'
  end

  def like_post
  	@post = Post.find(params[:like][:likeable_id])
    @post_like = @post.likes.build(params[:like])
    if @post_like.save
      respond_to do |format|
        format.html { redirect_to :action => 'view', :id => @post.id }
        format.json { render json: @post.id, status: :created }
      end
    end
  end

  def like_comment
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:like][:likeable_id])
    @comment_like = @comment.likes.build(params[:like])
    if @comment_like.save
      respond_to do |format|
        format.html { redirect_to :action => 'view', :id => @post.id }
        format.json { render json: @post.id, status: :created }
      end
    end
  end

  def like_like
    @like = Like.find(params[:like][:likeable_id])
    @post = Post.find(@like.likeable_id)
    @new_like = @like.likes.build(params[:like])
    if @new_like.save
      respond_to do |format|
        format.html { redirect_to :action => 'view', :id => @post.id }
        format.json { render json: @post.id, status: :created }
      end
    end
  end

  def new_comment
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment])
    @comment_total = 0
    if !@post.comments.empty?
      @comment_total += @post.comments.size
    end
    if !@post.child_comments.empty?
      @comment_total += @post.child_comments.size
    end
    if @comment.article_id.blank?
      @comment.article_id = @post.id
    end
    if @comment.save
      respond_to do |format|
        format.html { redirect_to :action => 'view', :id => @post.id }
        format.json { render json: @post.id, status: :created }
      end
    else
      @current_block_name = params[:current_block_name]
      @current_block_height = params[:current_block_height]
      @error = 'Please fill all fields in correct format'
      render :action => 'view'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div id="header">
	<div class="container">
		<div class="logo">
			<%= link_to "R Blog - Simple RoR-based Blog", root_path %>
		</div>

		<ul id="main_nav">
			<% if user_signed_in? %>
				<li>
					<%= link_to 'New Post', post_new_path, :class => 'menu_icon icon_post' %>
				</li>
				<li>
					<%= link_to 'My account', edit_user_registration_path, :class => 'menu_icon icon_profile' %>
				</li>
				<li>
					<%= link_to 'Sign out', destroy_user_session_path, :class => 'menu_icon icon_signout', :method=>'delete' %>
				</li>
			<% else %>
				<li>
					<%= link_to 'Sign up', new_user_registration_path, :class => 'menu_icon icon_signup' %>
				</li>
				<li>
					<%= link_to 'Sign in', new_user_session_path, :class => 'menu_icon icon_signin' %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

<div class="clear"></div>

app/views/post/_commentform.html.erb
<%= form_for([@post, Comment.new], :url => post_new_comment_path, :method => 'put') do |f| %>
  
  <%= hidden_field_tag :current_block_name, @current_block_name.nil? ? '' : @current_block_name %>
  <%= hidden_field_tag :current_block_height, @current_block_height.nil? ? '' : @current_block_height %>
  <% guest_name = @comment.author_name unless @comment.nil? %>
  <% guest_mail = @comment.author_mail unless @comment.nil? %>
  <% the_content = @comment.content unless @comment.nil? %>
  <% author_name = user_signed_in? ? current_user.name : guest_name %>
  <% author_mail = user_signed_in? ? current_user.email : guest_mail %>

  <% if !@error.nil? %>
    <div id="error_explanation">
      <h3><%= @error %></h3>
    </div>
  <% end %>
  
  <div class="form_hide">
	  <div class="form_block">
	    <%= hidden_field_tag :post_id, @post.id, :readonly => true %>
	  </div>
	  
	  <div class="form_block">
	    <div class="label"><%= f.label :article_id %></div>
	    <%= f.number_field :article_id, {:readonly => true, :class => 'input_comment'} %>
	  </div>
  </div>
  
  <div class="form_block">
    <div class="label"><%= f.label :author_name %></div>
    <%= f.text_field :author_name, {:size => 56, :value => author_name, :readonly => user_signed_in?} %>
  </div>
  
  <div class="form_block">
    <div class="label"><%= f.label :author_mail %></div>
    <%= f.text_field :author_mail, {:size => 56, :value => author_mail, :readonly => user_signed_in?} %>
  </div>
  
  <div class="form_block">
    <div class="label"><%= f.label :content %></div>
    <%= f.text_area :content, {:cols => 45, :value => the_content} %>
  </div>
  
  <div class="form_block">
    <div class="label"></div>
    <%= f.submit 'Save', :class => 'button icon_save' %>
    <%= submit_tag "Cancel", :type => 'button', :class => 'button_cancel new_comment_close' %>
  </div>
<% end %>

app/views/post/_form.html.erb
<%= form_for(@post, :url => post_new_path, :method => 'put') do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form_block">
    <div class="label"><%= f.label :author_name %></div>
    <%= f.text_field :author_name, :size => 112, :value => current_user.name, :readonly => true %>
  </div>
  
  <div class="form_block">
    <div class="label"><%= f.label :author_mail %></div>
    <%= f.text_field :author_mail, {:size => 112, :value => current_user.email, :readonly => true} %>
  </div>

  <div class="form_block">
    <div class="label"><%= f.label :title %></div>
    <%= f.text_field :title, :size => 112 %>
  </div>
  
  <div class="form_block">
    <div class="label"><%= f.label :content %></div>
    <%= f.text_area :content, :cols => 80 %>
  </div>
  
  <div class="form_block">
    <div class="label"><%= f.label :tag %></div>
    <%= f.text_field :tag, :size => 112 %>
  	<br /><i><span class="label"></span>(use comma for multiple tags)</i>
  </div>
  
  <div class="form_block">
    <div class="label"></div>
    <%= f.submit %>
  </div>
<% end %>

app/views/post/_likecommentform.html.erb
<%= form_for([comment, Like.new], {:url => post_like_comment_path, :method => 'put'}) do |f| %>
  <div class="form_hide">
		<div class="field">
			<%= hidden_field_tag :post_id, @post.id, :readonly => true %>
		</div>
		<div class="field">
			<%= f.label :likeable_id %><br />
			<%= f.number_field :likeable_id, {:value => comment.id, :readonly => true} %>
		</div>
		<div class="field">
			<%= f.label :user_id %><br />
			<%= f.text_field :user_id, {:value => current_user.id, :readonly => true} %>
		</div>
  </div>
  
  <% if !comment.likes.empty? && !comment.likes.where(:user_id => current_user.id).blank? %>
  	<span class="icon_liked" style="color:#646869;">You Liked This Comment</span> 
  <% else %>
  	<%= f.submit 'Like This Comment', :class => 'like_button icon_like' %> 
  <% end %>

<% end %>

app/views/post/_likeform.html.erb
<%= form_for([@post, Like.new], {:url => post_like_post_path, :method => 'put'}) do |f| %>
  <div class="form_hide">
    <div class="field">
      <%= f.label :likeable_id %><br />
      <%= f.number_field :likeable_id, {:value => @post.id, :readonly => true} %>
    </div>
    <div class="field">
      <%= f.label :user_id %><br />
      <%= f.text_field :user_id, {:value => current_user.id, :readonly => true} %>
    </div>
  </div>
  
  <% if !@post.likes.empty? && !@post.likes.where(:user_id => current_user.id).blank? %>
  	<span class="icon_liked" style="color:#646869;">You Liked This Post <span class="span_space">| </span></span> 
  <% else %>
  	<%= f.submit 'Like This Post', :class => 'like_button icon_like' %> <span style="color:#646869;">| </span> 
  <% end %>
<% end %>

app/views/post/_likelikeform.html.erb
<%= form_for(like.likes.new, {:url => post_like_like_path, :method => 'put'}) do |f| %>
  <div class="form_hide">
    <div class="field">
      <%= f.label :likeable_id %><br />
      <%= f.number_field :likeable_id, {:value => like.id, :readonly => true} %>
    </div>
    <div class="field">
      <%= f.label :user_id %><br />
      <%= f.text_field :user_id, {:value => current_user.id, :readonly => true} %>
    </div>
  </div>
  
  <% liked_name = User.find(like.user_id).name %>
  <% if !like.likes.empty? && !like.likes.where(:user_id => current_user.id).blank? %>
  	<span class="icon_liked" style="color:#646869;"><%= liked_name %></span> 
  <% else %>
  	<%= f.submit liked_name, :class => 'like_button icon_like' %>
  <% end %>
<% end %>

app/views/post/index.html.erb
<script type="text/javascript">

	function reload_data(){
		jQuery.get(document.location.href, function(data) {
			var new_post_list = jQuery(data).find('#main_page').html();
			jQuery('#main_page').html(new_post_list);
		});
	}

	var socket = io.connect('http://localhost:5001');

	socket.on('connect', function () {
		socket.on('post_created', function (data) {
			reload_data();
		});

		socket.on('post_deleted', function (data) {
			reload_data();
		});

		socket.on('post_updated', function (data) {
			reload_data();
		});

		var newly_deleted_post = jQuery('#flash_deleted');
		if((typeof newly_deleted_post.html() !== 'undefined') && (newly_deleted_post != null)){
			socket.emit('delete_post');
		}
	});

</script>

<div id="main_page">
<% @posts.each do |post| %>
	<div class="block_content">
		<h2>
			<%= link_to post.title, post_view_path(:id => post.id) %>
		</h2>
		<div class="post_content">
			<% if post.content.size > 560 %>
			<%= post.content.slice(0..560) %>...
			<%= link_to "read more", post_view_path(:id => post.id), :class => 'read_more' %>
			<% else %>
			<%= post.content %>
			<% end %>
		</div>
		<div class="post_info">
			<div class="post_created">
				<%= l post.created_at, :format => "%B %d, %Y" %>
				by <%= post.author_name %>
			</div>
			<div class="post_info_border"></div>
			<div class="comment_like_block">
				<% like_names = '0' %>
				<% if !post.likes.empty? %>
				<% like_names = post.likes.map{|el| User.find(el[:user_id]).name}.join(', ') %>
				<% end %>
				<span class="icon_like" title="<%= like_names %>">
					<%= !post.likes.empty? ? post.likes.size.to_s : '0' %>
				</span>
				<span class="icon_comment">
					<% comment_total = 0 %>
    				<% if !post.comments.empty? %>
      				<% comment_total += post.comments.size %>
    				<% end %>
    				<% if !post.child_comments.empty? %>
      				<% comment_total += post.child_comments.size %>
    				<% end %>
					<%= comment_total.to_s %>
				</span>
			</div>
			<div class="post_info_border"></div>
			<div>
				<% post_tags = post.tag.split(',') %>
				<div class="icon_tag">
				<% post_tags.each do |post_tag| %>
				<%= link_to post_tag.strip, {:controller => "post", :action => "index", :tag => post_tag.strip }, :title => post_tag.strip %>
				<% end %>
				</div>
			</div>
			<div class="post_info_border"></div>
			<% if user_signed_in? && (current_user.email == post.author_mail) %>
			<div>
				<%= link_to 'Edit', post_update_path(:id => post.id), {:class => 'icon_edit'} %>
				<%= link_to 'Delete', post_delete_path(:id => post.id), method: :delete, :class => 'icon_delete', data: { confirm: 'Are you sure?' } %>
			</div>
			<div class="post_info_border"></div>
			<% end %>
		</div>
	</div>
<% end %>
</div>

app/views/post/new.html.erb
<div class="block_content">

<h2>New post</h2>

<%= render 'form' %>

</div>

app/views/post/view.html.erb
<div class="block_content">

	<h2>
	  <%= link_to @post.title, post_view_path(:id => @post.id) %>
	</h2>

	<div class="post_content" style="margin-top: -20px;">
	  <%= simple_format(@post.content).html_safe %>
	</div>
	
	<div class="post_info">
		<div class="post_created">
			<%= l @post.created_at, :format => "%B %d, %Y" %>
			by <%= @post.author_name %>
		</div>
		<div class="post_info_border"></div>
		<div class="comment_like_block">
			<% like_names = '0' %>
			<% if !@post.likes.empty? %>
			<% like_names = @post.likes.map{|el| User.find(el[:user_id]).name}.join(', ') %>
			<% end %>
			<span id="side_like_block" class="icon_like" title="<%= like_names %>">
				<%= !@post.likes.empty? ? @post.likes.size.to_s : '0' %>
			</span>
			<span class="icon_comment">
				<%= @comment_total.to_s %>
			</span>
		</div>
		<div class="post_info_border"></div>
		<div>
			<% post_tags = @post.tag.split(',') %>
			<div class="icon_tag">
			<% post_tags.each do |post_tag| %>
			<%= link_to post_tag.strip, {:controller => "post", :action => "index", :tag => post_tag.strip } %>
			<% end %>
			</div>
		</div>
		<div class="post_info_border"></div>
		<% if user_signed_in? && (current_user.email == @post.author_mail) %>
		<div>
			<%= link_to 'Edit', post_update_path(:id => @post.id), {:class => 'icon_edit'} %>
			<%= link_to 'Delete', post_delete_path(:id => @post.id), method: :delete, :class => 'icon_delete', data: { confirm: 'Are you sure?' } %>
		</div>
		<div class="post_info_border"></div>
		<% end %>
	</div>
	<div class="show_comment_block">
		<div class="left_align">
			<span class="icon_like" id="post_like_block">
				<%= !@post.likes.empty? ? @post.likes.size.to_s : '0' %> Like(s)
			</span>
			<span class="icon_comment">
			<%= @comment_total.to_s %> Comment(s)
			</span>
			<% if user_signed_in? && !@post.likes.empty? %>
			<div id="likes_block">
				<% @post.likes.each do |post_like| %>
					<div class="likes_form">
						<%= render 'likelikeform', :like => post_like %>
					</div>
					<% unless post_like == @post.likes.last %>
						<span style="margin-left:-5px">, </span>
					<% end %>
				<% end %>
			</div>
			<% end %>
		</div>
		<div class="right_align">
			<% if user_signed_in? %>
			<%= render 'likeform' %>
			<% end %>
			<%= link_to 'Leave Comment', '#new_comment', {:class => 'new_comment_button', :id => 'new_comment_button'} %>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="list_comment_block">
	<% if !@post.comments.empty? %>
		<% @post.comments.each do |comment| %>
			<div class="comment_block" id=<%= 'comment_' + comment.id.to_s %>>
				<div class="comment_content">
					<div class="comment_content_text">
					<%= comment.content %>
					</div>
					<div class="comment_content_button">
						<% if user_signed_in? %>
						<%= render 'likecommentform', :comment => comment %> <span style="color:#646869;">|</span> 
						<% end %>
						<%= link_to 'Comment', '#new_subcomment', {:class => 'new_subcomment_button', :id => 'commentbutton_' + comment.id.to_s} %>
					</div>
				</div>
				<div class="comment_info">
					<%= comment.author_name %><br />
					<%= l comment.updated_at, :format => "%B %d, %Y / %H:%M" %>
					<div class="comment_info_border"></div>
					<% comment_like_names = '0' %>
					<% if !comment.likes.empty? %>
					<% comment_like_names = comment.likes.map{|el| User.find(el[:user_id]).name}.join(', ') %>
					<% end %>
					<span class="icon_like" title="<%= comment_like_names %>">
						<%= !comment.likes.empty? ? comment.likes.size.to_s : '0' %>
					</span>
				</div>
			</div>
			<% if !comment.comments.empty? %>
				<% comment.comments.each do |child_comment| %>
					<div class="sub_comment_block" id=<%= 'subcomment_' + child_comment.id.to_s %>>
						<div class="sub_comment_content">
							<div class="comment_content_text">
							<%= child_comment.content %>
							</div>
							<% if user_signed_in? %>
							<div class="comment_content_button">
								<%= render 'likecommentform', :comment => child_comment %>
							</div>
							<% end %>
						</div>
						<div class="sub_comment_info">
							<%= child_comment.author_name %><br />
							<%= l child_comment.updated_at, :format => "%B %d, %Y / %H:%M" %>
							<div class="comment_info_border"></div>
							<% subcomment_like_names = '0' %>
							<% if !child_comment.likes.empty? %>
							<% subcomment_like_names = child_comment.likes.map{|el| User.find(el[:user_id]).name}.join(', ') %>
							<% end %>
							<span class="icon_sublike" title="<%= subcomment_like_names %>">
								<%= !child_comment.likes.empty? ? child_comment.likes.size.to_s : '0' %>
							</span>
						</div>
					</div>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
	</div>
	
	<div class="new_comment_block" id="new_comment_block">
		<h2 class="new_comment_close">Leave Comment</h2>
		<div class="new_comment_form">
		<%= render 'commentform' %>
		</div>
	</div>
	
</div>

	<script type="text/javascript">
		function page_load_script(){

			jQuery('form').submit(function(event) {  
				var valuesToSubmit = jQuery(this).serialize();
				jQuery.ajax({
					url: jQuery(this).prop('action'),
					data: valuesToSubmit,
					method: 'put',
					dataType: "JSON"
				}).success(function(post_id){
					socket.emit('update_like_comment');
					reload_data();
				});
				event.preventDefault();
			});
			
			jQuery('#post_like_block').mouseenter(function(){
				if(jQuery('#side_like_block').text().indexOf('0') < 0 ){
					jQuery('#likes_block').show(function (){
						jQuery('.list_comment_block').slideUp();
						jQuery('.left_align .icon_comment').slideUp();
						jQuery('#new_comment_button').slideUp();
						jQuery('.span_space').slideUp();
						jQuery('.show_comment_block').css('margin-bottom', '35px');
					});
				}
			});
			jQuery('#likes_block').mouseleave(function(){
				jQuery('#likes_block').hide(function (){
					jQuery('.list_comment_block').slideDown();
					jQuery('.left_align .icon_comment').slideDown();
					jQuery('#new_comment_button').slideDown();
					jQuery('.span_space').slideDown();
					jQuery('.show_comment_block').css('margin-bottom', '0px');
				});
			});
			
			jQuery('#new_comment_block').hide();
			jQuery('.new_comment_close').css('cursor', 'pointer');

			if(jQuery('#current_block_name').val() != ''){
				jQuery('#new_comment_block').appendTo('#' + jQuery('#current_block_name').val());
			}else {
				jQuery('#new_comment_block').appendTo('.list_comment_block');
			}

			var has_errors = jQuery('#error_explanation').html();
			if((typeof has_errors !== 'undefined') && (has_errors != null)){
				jQuery('#new_comment_block').show();
				jQuery('html, body').animate({
					scrollTop: jQuery('#current_block_height').val()
				}, 2000);
			}
			
			jQuery('.new_comment_close').click(function(event){
				<% if user_signed_in? %>
					jQuery('.comment_content_button').slideDown();
					jQuery('.right_align').slideDown();
				<% else %>
					jQuery('#new_comment_button').slideDown();
					jQuery('.new_subcomment_button').slideDown();
				<% end %>
				if((typeof has_errors !== 'undefined') && (has_errors != null)){
					jQuery('#error_explanation').remove();
				}
				jQuery('#new_comment_block').slideUp();
				event.preventDefault();
				
			});
			
			jQuery('#new_comment_button').click(function(event){
				<% if user_signed_in? %>
					jQuery('.comment_content_button').slideUp();
					jQuery('.right_align').slideUp();
				<% else %>
					jQuery('#new_comment_button').slideUp();
					jQuery('.new_subcomment_button').slideUp();
				<% end %>
				jQuery('#new_comment_block').css('margin-left', '40px');
				jQuery('#new_comment_block').appendTo('.list_comment_block');
				jQuery('.input_comment').val('');
				jQuery('#new_comment_block').slideDown(function(){
					var current_height = jQuery('.block_content')[0].scrollHeight;
					jQuery('#current_block_height').val(current_height);
					jQuery('html, body').animate({
						scrollTop: current_height
					}, 2000);
				});
				event.preventDefault();
			});
			
			jQuery('.new_subcomment_button').click(function(event){
				<% if user_signed_in? %>
					jQuery('.comment_content_button').slideUp();
					jQuery('.right_align').slideUp();
				<% else %>
					jQuery('#new_comment_button').slideUp();
					jQuery('.new_subcomment_button').slideUp();
				<% end %>
				var parent_block = jQuery(this).parent().parent().parent();
				var comment_id = jQuery(this).prop('id').split('commentbutton_')[1];
				var post_content_height = jQuery('.post_content')[0].scrollHeight;
				var show_comment_height = jQuery('.show_comment_block')[0].scrollHeight;
				var parent_id = parent_block.prop('id');
				if(parent_id.indexOf('subcomment') > -1){
					jQuery('#new_comment_block').css('margin-left', '0px');
				}else {
					jQuery('#new_comment_block').css('margin-left', '40px');
				}
				
				var prev_block_height = 0;
				if(parent_block.prevAll().length > 0){
					parent_block.prevAll().each(function (){
						prev_block_height += jQuery(this)[0].scrollHeight;
					});
				}
				var new_scroll_height = post_content_height + show_comment_height + prev_block_height + 160;
				
				jQuery('#new_comment_block').appendTo(parent_block);
				jQuery('#current_block_name').val(parent_id);
				
				jQuery('.input_comment').val(comment_id);
				
				jQuery('#new_comment_block').slideDown(function(){
					jQuery('#current_block_height').val(new_scroll_height);
					jQuery('html, body').animate({
						scrollTop: new_scroll_height
					}, 2000);
				});
				event.preventDefault();
			});
		}

		function reload_data(){
			jQuery.get(document.location.href, function(data) {
				var new_post_contents = jQuery(data).find('.block_content').html();
				jQuery('.block_content').html(new_post_contents);
				page_load_script();
			});
		}

		var socket = io.connect('http://localhost:5001');

		socket.on('connect', function () {

			var newly_created_post = jQuery('#flash_notice');
			if((typeof newly_created_post.html() !== 'undefined') && (newly_created_post != null)){
				socket.emit('new_post', '<%= @post.id %>');
			}

			var newly_updated_post = jQuery('#flash_updated');
			if((typeof newly_updated_post.html() !== 'undefined') && (newly_updated_post != null)){
				socket.emit('update_post');
			}

			socket.on('post_liked_or_commented', function (data) {
				reload_data();
			});

		});

		jQuery(document).ready(function(){
		
			page_load_script();
			
		});
	</script>